![](10_permuting.png)
![](10_permuting_constraints.png)

In [6]:
A = [1,2]
B = [1,2,3]
C = [1,2,3,4]

A' = 12, 21
B' = 1 32, 32 1, 23 1, 
    12 3, 3 12, 3 21

C' = 1 234, 234 1,
    12 34, 34 12
    123 4, 4 123
    1234




In [7]:
def permute(arr):
    if len(arr) == 1:
        yield arr
    else:
        for i in range(len(arr)):
            for perm in permute(arr[:i] + arr[i+1:]):
                yield [arr[i]] + perm

for i in permute(C):
    print(i)


[1, 2, 3, 4]
[1, 2, 4, 3]
[1, 3, 2, 4]
[1, 3, 4, 2]
[1, 4, 2, 3]
[1, 4, 3, 2]
[2, 1, 3, 4]
[2, 1, 4, 3]
[2, 3, 1, 4]
[2, 3, 4, 1]
[2, 4, 1, 3]
[2, 4, 3, 1]
[3, 1, 2, 4]
[3, 1, 4, 2]
[3, 2, 1, 4]
[3, 2, 4, 1]
[3, 4, 1, 2]
[3, 4, 2, 1]
[4, 1, 2, 3]
[4, 1, 3, 2]
[4, 2, 1, 3]
[4, 2, 3, 1]
[4, 3, 1, 2]
[4, 3, 2, 1]


In [19]:
A = [2,1,3]
B = [7,8,9]     
C = [1,2,2,1]
D = [3,3,3,4]  

k = 10


def twoArrays(A, B, k):
    exists = 'NO'
    for A_ in permute(A):
        for B_ in permute(B):
            cnt = 0
            for i in range(len(A)):
                if A_[i] + B_[i] >= k:
                    cnt += 1
            if cnt == len(A):
                exists = 'YES'
                break
        if exists == 'YES':
                break
    return exists

print(twoArrays(A, B, 10))
print(twoArrays(C,D,5))

    

YES
NO


In [67]:
import time
import functools
def stop_watch(func):
  @functools.wraps(func)
  def wrapper(*args, **kwargs):
    start = time.perf_counter() # Start Time
    result = func(*args, **kwargs)
    end = time.perf_counter() # End Time
    print(f"{func.__name__} ran in {end - start:0.4f} seconds")
    return result
  return wrapper

@stop_watch
def some_function(sec: int):
  time.sleep(sec)

if __name__ == "__main__":
  some_function(5)

some_function ran in 5.0017 seconds


In [51]:
A = [2,1,3]
B = [7,8,9]     
C = [1,2,2,1]
D = [3,3,3,4]  

import random
n = 6
E = [random.randint(0, 10) for i in range(n)]
F = [random.randint(0, 10) for i in range(n)]
print('E=', E)
print('F=', F)

@stop_watch
def twoArrays(k, A, B):
    exists = 'NO'
    for A_ in permute(A):
        for B_ in permute(B):
            cnt = 0
            for i in range(len(A)):
                if A_[i] + B_[i] >= k:
                    cnt += 1
            if cnt == len(A):
                exists = 'YES'
                break
        if exists == 'YES':
                break
    return exists

print(twoArrays(10, A, B))
print(twoArrays(5,C,D))
print(twoArrays(8,E,F))


E= [8, 1, 2, 10, 3, 4]
F= [9, 0, 10, 2, 10, 1]
function twoArrays ran in 0.0001 seconds
YES
function twoArrays ran in 0.0035 seconds
NO
function twoArrays ran in 1.3609 seconds
NO


In [80]:

import numpy as np

@stop_watch
def twoArrays(k, A, B):
    B = np.array(B)
    K = np.ones(len(A)) * k
    exists = 'NO'
    for A_ in permute(A):
        A_ = np.array(A_)
        if (A_+ B >= K).all():
            exists = 'YES'
            break
        
    return exists

A = [2,1,3]
B = [7,8,9]     
C = [1,2,2,1]
D = [3,3,3,4]  

import random
n = 6
E = [random.randint(0, 10) for i in range(n)]
F = [random.randint(0, 10) for i in range(n)]

print(twoArrays(10, A, B))
print(twoArrays(5, C, D))

print('E=', E)
print('F=', F)
print(twoArrays(8, E, F))

[10. 10. 10.]
twoArrays ran in 0.0008 seconds
YES
[5. 5. 5. 5.]
twoArrays ran in 0.0008 seconds
NO
E= [2, 0, 3, 10, 1, 8]
F= [0, 5, 5, 2, 9, 4]
[8. 8. 8. 8. 8. 8.]
twoArrays ran in 0.0113 seconds
NO


In [90]:
@stop_watch
def twoArrays(k, A, B):
    A.sort()
    B = sorted(B, reverse=True)
    print(A)
    print(B)
    for i in range(len(A)):
        if A[i] + B[i] < k:
            return 'NO'
    return 'YES'


A = [2,1,3]
B = [7,8,9]     
C = [1,2,2,1]
D = [3,3,3,4]  

import random
n = 6
E = [random.randint(0, 10) for i in range(n)]
F = [random.randint(0, 10) for i in range(n)]

print(twoArrays(10, A, B))
print(twoArrays(5, C, D))

print('E=', E)
print('F=', F)
print(twoArrays(10, E, F))

[1, 2, 3]
[9, 8, 7]
twoArrays ran in 0.0001 seconds
YES
[1, 1, 2, 2]
[4, 3, 3, 3]
twoArrays ran in 0.0000 seconds
NO
E= [6, 8, 3, 9, 7, 8]
F= [10, 0, 5, 3, 3, 6]
[3, 6, 7, 8, 8, 9]
[10, 6, 5, 3, 3, 0]
twoArrays ran in 0.0001 seconds
NO
