In [44]:
# Starting code

import numpy as np
import math

def mutual_information(arr):
    n = len(arr)
    m = len(arr[0])
    if n > 0 & m > 0:
        
        pi, pj = calc_p(arr)

        return calc_pij(arr) - calc_(pi) - calc_(pj)
        
    else:
        return 0.

def calc_p(arr):
    n = len(arr)
    m = len(arr[0])
    pi = np.zeros(n)
    pj = np.zeros(m)
    
    for i, row in enumerate(arr):
        for j, element in enumerate(row):
            pi[i] += element 
            pj[j] += element
    
    return pi, pj

def calc_(p):
    s = 0.
    for i, element in enumerate(p):
            s += element * np.log(element)
    return s

def calc_pij(arr):
    n = len(arr)
    m = len(arr[0])
    pij = np.zeros((n,m))

    for i, row in enumerate(arr):
        for j, element in enumerate(row):
            pij[i,j] += element * np.log(element)

    return pij

In [45]:
arr = np.array([[2,3,5,4], 
                [3,7,2,1], 
                [7,3,1,2]])

In [51]:
calc_p(arr)

(array([14., 13., 13.]), array([12., 13.,  8.,  7.]))

In [48]:
mutual_information(arr)

0.0

In [43]:
pj

array([0., 0., 0., 0.])

In [46]:
for i, row in enumerate(arr):
    for j, element in enumerate(row):
        pi[i] += element 
        pj[j] += element
pi

array([14., 13., 13.])

In [33]:
n, m = len(arr), len(arr[0])
n,m

(3, 4)

In [47]:
calc_p(arr)

(array([14., 13., 13.]), array([12., 13.,  8.,  7.]))