# Mutual Information

In [42]:
import numpy as np
import math

def mutual_information(arr):
    n, m = len(arr), len(arr[0])
    print(n,',',m)
    if n > 0 and m > 0:
        pi, pj = calc_p(arr)
        return calc_pij(arr) - calc_(pi) - calc_(pj)
    else:
        return 0.01

def calc_p(arr):
    n = len(arr)
    m = len(arr[0])
    pi = np.zeros(n)
    pj = np.zeros(m)
    
    for i, row in enumerate(arr):
        for j, element in enumerate(row):
            pi[i] += element 
            pj[j] += element
    
    return pi, pj

def calc_(p):
    s = 0.
    for i, element in enumerate(p):
            s += element * np.log(element)
    return s

def calc_pij(arr):
    n = len(arr)
    m = len(arr[0])
    pij = np.zeros((n,m))

    for i, row in enumerate(arr):
        for j, element in enumerate(row):
            pij[i,j] += element * np.log(element)

    return pij

In [43]:
ex1 = np.array([[2,3,4], 
                [3,2,1], 
                [7,1,2]])


ex2 = np.array([[2,3,5,4], 
                [3,7,2,1], 
                [7,3,1,2],
                [4,8,9,3]])

arr = ex1

In [44]:
calc_p(arr)

(array([ 9.,  6., 10.]), array([12.,  6.,  7.]))

In [45]:
mutual_information(arr)

3 , 3


array([[-106.35594224, -104.44639973, -102.19705915],
       [-104.44639973, -106.35594224, -107.7422366 ],
       [ -94.12086555, -107.7422366 , -106.35594224]])

In [46]:
n = len(arr)
m = len(arr[0])
pi = np.zeros(n)
pj = np.zeros(m)
for i, row in enumerate(arr):
    for j, element in enumerate(row):
        pi[i] += element 
        pj[j] += element
pi

array([ 9.,  6., 10.])

In [47]:
n, m = len(arr), len(arr[0])
n,m

(3, 3)

In [48]:
calc_p(arr)

(array([ 9.,  6., 10.]), array([12.,  6.,  7.]))